'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Messages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MiYABiS.TfCommand.Messages", GetType(Messages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  checkin に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property Caption001() As String
            Get
                Return ResourceManager.GetString("Caption001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  compare に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property Caption002() As String
            Get
                Return ResourceManager.GetString("Caption002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Resolving conflicts に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property Caption003() As String
            Get
                Return ResourceManager.GetString("Caption003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  shelve に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property Caption004() As String
            Get
                Return ResourceManager.GetString("Caption004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Server and are different . に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property I001() As String
            Get
                Return ResourceManager.GetString("I001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  checked out . に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property I002() As String
            Get
                Return ResourceManager.GetString("I002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  was back to the original . に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property I003() As String
            Get
                Return ResourceManager.GetString("I003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  added to the management under the TFS. Please check -in . に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property I004() As String
            Get
                Return ResourceManager.GetString("I004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  no different に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property I005() As String
            Get
                Return ResourceManager.GetString("I005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Operation confirm message に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property MessageBoxTitle() As String
            Get
                Return ResourceManager.GetString("MessageBoxTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Are you sure you want to be returned to the original ?
        '''Change what you will be lost .
        '''
        '''( When adding is not lost changes by simply goes out of TFS management . ) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property Q001() As String
            Get
                Return ResourceManager.GetString("Q001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Is being edited .
        '''The Are you sure you want to {0} to save ? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property Q002() As String
            Get
                Return ResourceManager.GetString("Q002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  The Are you sure you want to restore the shelve ?
        '''Change what you will be lost . に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property Q003() As String
            Get
                Return ResourceManager.GetString("Q003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please enter the name you want to change . に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public Shared ReadOnly Property Q004() As String
            Get
                Return ResourceManager.GetString("Q004", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
